service: webshop-html-scraper
# app and org for use with dashboard.serverless.com
app: scraper-webshop
org: patrickkompier

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
  lambdaScrape:
    handler: launcher.scrape

package:
  include:
    - handler.py
    - launcher.py
    - lxml/
    - webscraper/
    - webscraper/**
    - scrapy.cfg    
  exclude:
    - "./**"
    - webscraper/__pycache__/

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true # Omits tests, __pycache__, *.pyc etc from dependencies
    fileName: requirements.txt